### YamlMime:ManagedReference
items:
- uid: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  commentId: T:BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  id: Settings.TouchToggleMode
  parent: BennyKok.RuntimeDebug.Data
  children:
  - BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.AlwaysOn
  - BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.MobileOnly
  - BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.Off
  langs:
  - csharp
  - vb
  name: Settings.TouchToggleMode
  nameWithType: Settings.TouchToggleMode
  fullName: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  type: Enum
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: TouchToggleMode
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 101
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  syntax:
    content: public enum TouchToggleMode
    content.vb: Public Enum TouchToggleMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.MobileOnly
  commentId: F:BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.MobileOnly
  id: MobileOnly
  parent: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  langs:
  - csharp
  - vb
  name: MobileOnly
  nameWithType: Settings.TouchToggleMode.MobileOnly
  fullName: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.MobileOnly
  type: Field
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: MobileOnly
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 106
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  summary: "\nThe UI toggle will only be enabled when the build platfrom is a known mobile platform\n"
  example: []
  syntax:
    content: MobileOnly = 0
    return:
      type: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.AlwaysOn
  commentId: F:BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.AlwaysOn
  id: AlwaysOn
  parent: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  langs:
  - csharp
  - vb
  name: AlwaysOn
  nameWithType: Settings.TouchToggleMode.AlwaysOn
  fullName: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.AlwaysOn
  type: Field
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: AlwaysOn
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 111
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  summary: "\nThe UI toggle is enabled no matter what build platfrom\n"
  example: []
  syntax:
    content: AlwaysOn = 1
    return:
      type: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.Off
  commentId: F:BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.Off
  id: Off
  parent: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  langs:
  - csharp
  - vb
  name: Off
  nameWithType: Settings.TouchToggleMode.Off
  fullName: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode.Off
  type: Field
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: Off
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 113
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  syntax:
    content: Off = 2
    return:
      type: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BennyKok.RuntimeDebug.Data
  commentId: N:BennyKok.RuntimeDebug.Data
  name: BennyKok.RuntimeDebug.Data
  nameWithType: BennyKok.RuntimeDebug.Data
  fullName: BennyKok.RuntimeDebug.Data
- uid: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  commentId: T:BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
  parent: BennyKok.RuntimeDebug.Data
  name: Settings.TouchToggleMode
  nameWithType: Settings.TouchToggleMode
  fullName: BennyKok.RuntimeDebug.Data.Settings.TouchToggleMode
