### YamlMime:ManagedReference
items:
- uid: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  commentId: T:BennyKok.RuntimeDebug.Data.Settings.EnableMode
  id: Settings.EnableMode
  parent: BennyKok.RuntimeDebug.Data
  children:
  - BennyKok.RuntimeDebug.Data.Settings.EnableMode.AutoOn
  - BennyKok.RuntimeDebug.Data.Settings.EnableMode.Off
  - BennyKok.RuntimeDebug.Data.Settings.EnableMode.OnInDevelopmentBuild
  langs:
  - csharp
  - vb
  name: Settings.EnableMode
  nameWithType: Settings.EnableMode
  fullName: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  type: Enum
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: EnableMode
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 116
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  syntax:
    content: public enum EnableMode
    content.vb: Public Enum EnableMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: BennyKok.RuntimeDebug.Data.Settings.EnableMode.AutoOn
  commentId: F:BennyKok.RuntimeDebug.Data.Settings.EnableMode.AutoOn
  id: AutoOn
  parent: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  langs:
  - csharp
  - vb
  name: AutoOn
  nameWithType: Settings.EnableMode.AutoOn
  fullName: BennyKok.RuntimeDebug.Data.Settings.EnableMode.AutoOn
  type: Field
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: AutoOn
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 121
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  summary: "\nThe debug system is auto injected to the scene\n"
  example: []
  syntax:
    content: AutoOn = 0
    return:
      type: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BennyKok.RuntimeDebug.Data.Settings.EnableMode.Off
  commentId: F:BennyKok.RuntimeDebug.Data.Settings.EnableMode.Off
  id: Off
  parent: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  langs:
  - csharp
  - vb
  name: Off
  nameWithType: Settings.EnableMode.Off
  fullName: BennyKok.RuntimeDebug.Data.Settings.EnableMode.Off
  type: Field
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: Off
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 126
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  summary: "\nThe debug system is off by default\n"
  example: []
  syntax:
    content: Off = 1
    return:
      type: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BennyKok.RuntimeDebug.Data.Settings.EnableMode.OnInDevelopmentBuild
  commentId: F:BennyKok.RuntimeDebug.Data.Settings.EnableMode.OnInDevelopmentBuild
  id: OnInDevelopmentBuild
  parent: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  langs:
  - csharp
  - vb
  name: OnInDevelopmentBuild
  nameWithType: Settings.EnableMode.OnInDevelopmentBuild
  fullName: BennyKok.RuntimeDebug.Data.Settings.EnableMode.OnInDevelopmentBuild
  type: Field
  source:
    remote:
      path: Runtime/Data/Settings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: OnInDevelopmentBuild
    path: ../Assets/Plugins/RuntimeDebugAction/Runtime/Data/Settings.cs
    startLine: 131
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BennyKok.RuntimeDebug.Data
  summary: "\nThe debug system is only auto injected in &apos;Development Build&apos; \n"
  example: []
  syntax:
    content: OnInDevelopmentBuild = 2
    return:
      type: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BennyKok.RuntimeDebug.Data
  commentId: N:BennyKok.RuntimeDebug.Data
  name: BennyKok.RuntimeDebug.Data
  nameWithType: BennyKok.RuntimeDebug.Data
  fullName: BennyKok.RuntimeDebug.Data
- uid: BennyKok.RuntimeDebug.Data.Settings.EnableMode
  commentId: T:BennyKok.RuntimeDebug.Data.Settings.EnableMode
  parent: BennyKok.RuntimeDebug.Data
  name: Settings.EnableMode
  nameWithType: Settings.EnableMode
  fullName: BennyKok.RuntimeDebug.Data.Settings.EnableMode
