### YamlMime:ManagedReference
items:
- uid: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  commentId: T:BK.RDAction.Data.RDActionSettings.TouchToggleMode
  id: RDActionSettings.TouchToggleMode
  parent: BK.RDAction.Data
  children:
  - BK.RDAction.Data.RDActionSettings.TouchToggleMode.Always
  - BK.RDAction.Data.RDActionSettings.TouchToggleMode.MobileOnly
  langs:
  - csharp
  - vb
  name: RDActionSettings.TouchToggleMode
  nameWithType: RDActionSettings.TouchToggleMode
  fullName: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  type: Enum
  source:
    remote:
      path: Runtime/Data/RDActionSettings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: TouchToggleMode
    path: ../Assets/Plugins/Runtime Debug Action/Runtime/Data/RDActionSettings.cs
    startLine: 49
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BK.RDAction.Data
  syntax:
    content: public enum TouchToggleMode
    content.vb: Public Enum TouchToggleMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: BK.RDAction.Data.RDActionSettings.TouchToggleMode.MobileOnly
  commentId: F:BK.RDAction.Data.RDActionSettings.TouchToggleMode.MobileOnly
  id: MobileOnly
  parent: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  langs:
  - csharp
  - vb
  name: MobileOnly
  nameWithType: RDActionSettings.TouchToggleMode.MobileOnly
  fullName: BK.RDAction.Data.RDActionSettings.TouchToggleMode.MobileOnly
  type: Field
  source:
    remote:
      path: Runtime/Data/RDActionSettings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: MobileOnly
    path: ../Assets/Plugins/Runtime Debug Action/Runtime/Data/RDActionSettings.cs
    startLine: 51
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BK.RDAction.Data
  syntax:
    content: MobileOnly = 0
    return:
      type: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: BK.RDAction.Data.RDActionSettings.TouchToggleMode.Always
  commentId: F:BK.RDAction.Data.RDActionSettings.TouchToggleMode.Always
  id: Always
  parent: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  langs:
  - csharp
  - vb
  name: Always
  nameWithType: RDActionSettings.TouchToggleMode.Always
  fullName: BK.RDAction.Data.RDActionSettings.TouchToggleMode.Always
  type: Field
  source:
    remote:
      path: Runtime/Data/RDActionSettings.cs
      branch: master
      repo: https://gitlab.com/BennyKok/unity-runtime-debug-action.git
    id: Always
    path: ../Assets/Plugins/Runtime Debug Action/Runtime/Data/RDActionSettings.cs
    startLine: 51
  assemblies:
  - com.bennykok.runtime-debug-action
  namespace: BK.RDAction.Data
  syntax:
    content: Always = 1
    return:
      type: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: BK.RDAction.Data
  commentId: N:BK.RDAction.Data
  name: BK.RDAction.Data
  nameWithType: BK.RDAction.Data
  fullName: BK.RDAction.Data
- uid: BK.RDAction.Data.RDActionSettings.TouchToggleMode
  commentId: T:BK.RDAction.Data.RDActionSettings.TouchToggleMode
  parent: BK.RDAction.Data
  name: RDActionSettings.TouchToggleMode
  nameWithType: RDActionSettings.TouchToggleMode
  fullName: BK.RDAction.Data.RDActionSettings.TouchToggleMode
